apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "asterferry-node.fullname" . }}-state
spec:
  accessModes: [ReadWriteOnce]
  {{- if .Values.stateStorageClass }}
  storageClassName: {{ .Values.stateStorageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.stateSize }}
