apiVersion: v1
kind: Service
metadata:
  name: {{ include "asterferry-node.fullname" . }}
spec:
  selector: { app.kubernetes.io/name: {{ include "asterferry-node.name" . }} }
  ports:
    - name: data
      port: {{ .Values.dataPort }}
      targetPort: data
      protocol: UDP
