// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.2
// source: afdp/v1/data.proto

package afdpv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SessionHello struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AssignmentId string   `protobuf:"bytes,1,opt,name=assignment_id,json=assignmentId,proto3" json:"assignment_id,omitempty"`
	Generation   uint64   `protobuf:"varint,2,opt,name=generation,proto3" json:"generation,omitempty"`
	AgentId      string   `protobuf:"bytes,3,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Capabilities []string `protobuf:"bytes,4,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
}

func (x *SessionHello) Reset() {
	*x = SessionHello{}
	if protoimpl.UnsafeEnabled {
		mi := &file_afdp_v1_data_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SessionHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionHello) ProtoMessage() {}

func (x *SessionHello) ProtoReflect() protoreflect.Message {
	mi := &file_afdp_v1_data_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionHello.ProtoReflect.Descriptor instead.
func (*SessionHello) Descriptor() ([]byte, []int) {
	return file_afdp_v1_data_proto_rawDescGZIP(), []int{0}
}

func (x *SessionHello) GetAssignmentId() string {
	if x != nil {
		return x.AssignmentId
	}
	return ""
}

func (x *SessionHello) GetGeneration() uint64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *SessionHello) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *SessionHello) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type SessionAccept struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AssignmentId string   `protobuf:"bytes,1,opt,name=assignment_id,json=assignmentId,proto3" json:"assignment_id,omitempty"`
	Generation   uint64   `protobuf:"varint,2,opt,name=generation,proto3" json:"generation,omitempty"`
	Capabilities []string `protobuf:"bytes,3,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	ServiceIds   []string `protobuf:"bytes,4,rep,name=service_ids,json=serviceIds,proto3" json:"service_ids,omitempty"`
}

func (x *SessionAccept) Reset() {
	*x = SessionAccept{}
	if protoimpl.UnsafeEnabled {
		mi := &file_afdp_v1_data_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SessionAccept) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionAccept) ProtoMessage() {}

func (x *SessionAccept) ProtoReflect() protoreflect.Message {
	mi := &file_afdp_v1_data_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionAccept.ProtoReflect.Descriptor instead.
func (*SessionAccept) Descriptor() ([]byte, []int) {
	return file_afdp_v1_data_proto_rawDescGZIP(), []int{1}
}

func (x *SessionAccept) GetAssignmentId() string {
	if x != nil {
		return x.AssignmentId
	}
	return ""
}

func (x *SessionAccept) GetGeneration() uint64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *SessionAccept) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *SessionAccept) GetServiceIds() []string {
	if x != nil {
		return x.ServiceIds
	}
	return nil
}

type OpenMetadata struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Protocol  string `protobuf:"bytes,1,opt,name=protocol,proto3" json:"protocol,omitempty"`
	ServiceId string `protobuf:"bytes,2,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	Target    string `protobuf:"bytes,3,opt,name=target,proto3" json:"target,omitempty"`
	FlowId    uint64 `protobuf:"varint,4,opt,name=flow_id,json=flowId,proto3" json:"flow_id,omitempty"`
	// Egress opens are Agent proxy streams that must be authorized by the
	// assignment but are not tied to a reverse Service document.  They are
	// explicitly marked so a peer cannot smuggle an arbitrary target through a
	// reverse-service identifier.
	Egress bool `protobuf:"varint,5,opt,name=egress,proto3" json:"egress,omitempty"`
}

func (x *OpenMetadata) Reset() {
	*x = OpenMetadata{}
	if protoimpl.UnsafeEnabled {
		mi := &file_afdp_v1_data_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OpenMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenMetadata) ProtoMessage() {}

func (x *OpenMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_afdp_v1_data_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenMetadata.ProtoReflect.Descriptor instead.
func (*OpenMetadata) Descriptor() ([]byte, []int) {
	return file_afdp_v1_data_proto_rawDescGZIP(), []int{2}
}

func (x *OpenMetadata) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *OpenMetadata) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *OpenMetadata) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *OpenMetadata) GetFlowId() uint64 {
	if x != nil {
		return x.FlowId
	}
	return 0
}

func (x *OpenMetadata) GetEgress() bool {
	if x != nil {
		return x.Egress
	}
	return false
}

var File_afdp_v1_data_proto protoreflect.FileDescriptor

var file_afdp_v1_data_proto_rawDesc = []byte{
	0x0a, 0x12, 0x61, 0x66, 0x64, 0x70, 0x2f, 0x76, 0x31, 0x2f, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x12, 0x61, 0x73, 0x74, 0x65, 0x72, 0x66, 0x65, 0x72, 0x72, 0x79,
	0x2e, 0x61, 0x66, 0x64, 0x70, 0x2e, 0x76, 0x31, 0x22, 0x92, 0x01, 0x0a, 0x0c, 0x53, 0x65, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x12, 0x23, 0x0a, 0x0d, 0x61, 0x73, 0x73,
	0x69, 0x67, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0c, 0x61, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x1e,
	0x0a, 0x0a, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x0a, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x19,
	0x0a, 0x08, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x22, 0x0a, 0x0c, 0x63, 0x61, 0x70,
	0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x69, 0x65, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x0c, 0x63, 0x61, 0x70, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x69, 0x65, 0x73, 0x22, 0x99, 0x01,
	0x0a, 0x0d, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x41, 0x63, 0x63, 0x65, 0x70, 0x74, 0x12,
	0x23, 0x0a, 0x0d, 0x61, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x61, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x6d, 0x65,
	0x6e, 0x74, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x22, 0x0a, 0x0c, 0x63, 0x61, 0x70, 0x61, 0x62, 0x69, 0x6c, 0x69,
	0x74, 0x69, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0c, 0x63, 0x61, 0x70, 0x61,
	0x62, 0x69, 0x6c, 0x69, 0x74, 0x69, 0x65, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0a, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x73, 0x22, 0x92, 0x01, 0x0a, 0x0c, 0x4f, 0x70,
	0x65, 0x6e, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x12, 0x17, 0x0a,
	0x07, 0x66, 0x6c, 0x6f, 0x77, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06,
	0x66, 0x6c, 0x6f, 0x77, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x67, 0x72, 0x65, 0x73, 0x73,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x65, 0x67, 0x72, 0x65, 0x73, 0x73, 0x42, 0x24,
	0x5a, 0x22, 0x61, 0x73, 0x74, 0x65, 0x72, 0x66, 0x65, 0x72, 0x72, 0x79, 0x2f, 0x69, 0x6e, 0x74,
	0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x61, 0x66, 0x64, 0x70, 0x2f, 0x76, 0x31, 0x3b, 0x61, 0x66,
	0x64, 0x70, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_afdp_v1_data_proto_rawDescOnce sync.Once
	file_afdp_v1_data_proto_rawDescData = file_afdp_v1_data_proto_rawDesc
)

func file_afdp_v1_data_proto_rawDescGZIP() []byte {
	file_afdp_v1_data_proto_rawDescOnce.Do(func() {
		file_afdp_v1_data_proto_rawDescData = protoimpl.X.CompressGZIP(file_afdp_v1_data_proto_rawDescData)
	})
	return file_afdp_v1_data_proto_rawDescData
}

var file_afdp_v1_data_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_afdp_v1_data_proto_goTypes = []interface{}{
	(*SessionHello)(nil),  // 0: asterferry.afdp.v1.SessionHello
	(*SessionAccept)(nil), // 1: asterferry.afdp.v1.SessionAccept
	(*OpenMetadata)(nil),  // 2: asterferry.afdp.v1.OpenMetadata
}
var file_afdp_v1_data_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_afdp_v1_data_proto_init() }
func file_afdp_v1_data_proto_init() {
	if File_afdp_v1_data_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_afdp_v1_data_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SessionHello); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_afdp_v1_data_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SessionAccept); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_afdp_v1_data_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OpenMetadata); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_afdp_v1_data_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_afdp_v1_data_proto_goTypes,
		DependencyIndexes: file_afdp_v1_data_proto_depIdxs,
		MessageInfos:      file_afdp_v1_data_proto_msgTypes,
	}.Build()
	File_afdp_v1_data_proto = out.File
	file_afdp_v1_data_proto_rawDesc = nil
	file_afdp_v1_data_proto_goTypes = nil
	file_afdp_v1_data_proto_depIdxs = nil
}
